/**
 * Whitelist of columns the proposal engine may write, per table.
 *
 * Two reasons this is explicit rather than derived:
 *   - the model must not be able to set id, workspace_id, timestamps or any
 *     column that would let a proposal escape its workspace or forge provenance;
 *   - a "label" reference is resolved by the server into a real foreign key, so
 *     the model never supplies a row id.
 */

/** Model-supplied label fields, mapped to the real foreign key column. */
export const LABEL_REFERENCES: Record<string, { column: string; kind: 'entity' | 'evidence' | 'artifact' | 'signal' | 'interaction' | 'opportunity' | 'action' | 'business_unit' | 'finding' }> = {
  // A citation names the finding it belongs to. Resolved by label like every
  // other non-entity reference: it becomes a dependency on the finding item, so
  // a citation can never be written before the finding it cites.
  finding_label: { column: 'finding_id', kind: 'finding' },
  related_entity_label: { column: 'related_entity_id', kind: 'entity' },
  entity_label: { column: 'entity_id', kind: 'entity' },
  person_entity_label: { column: 'person_entity_id', kind: 'entity' },
  organization_entity_label: { column: 'organization_entity_id', kind: 'entity' },
  external_entity_label: { column: 'external_entity_id', kind: 'entity' },
  candidate_entity_label: { column: 'candidate_entity_id', kind: 'entity' },
  evidence_label: { column: 'evidence_id', kind: 'evidence' },
  source_evidence_label: { column: 'source_evidence_id', kind: 'evidence' },
  artifact_label: { column: 'artifact_id', kind: 'artifact' },
  source_artifact_label: { column: 'source_artifact_id', kind: 'artifact' },
  signal_label: { column: 'signal_id', kind: 'signal' },
  source_signal_label: { column: 'source_signal_id', kind: 'signal' },
  interaction_label: { column: 'related_interaction_id', kind: 'interaction' },
  opportunity_label: { column: 'related_opportunity_id', kind: 'opportunity' },
  action_label: { column: 'related_action_id', kind: 'action' },
  business_unit_label: { column: 'business_unit_id', kind: 'business_unit' },
  matched_entity_label: { column: 'matched_entity_id', kind: 'entity' },
  internal_business_unit_label: { column: 'internal_business_unit_id', kind: 'business_unit' },
};

export interface TableSpec {
  /** Columns a proposal may set. */
  writable: string[];
  /** Columns required for a create. */
  required: string[];
  /** Column holding the human-readable name, used for readback and dedup. */
  labelColumn: string | null;
  /** Column that must hold a slug, generated by the server from labelColumn. */
  slugColumn: string | null;
  /** Columns that are natural keys within a workspace, for idempotent creates. */
  naturalKey: string[];
}

export const TABLE_SPECS: Record<string, TableSpec> = {
  entities: {
    writable: [
      'entity_type', 'display_name', 'description', 'primary_url', 'region', 'country',
      'research_status', 'relationship_status', 'relationship_confidence', 'status',
      'visibility', 'external_use_status', 'sensitivity', 'provenance_note', 'capture_source',
      'source_evidence_id',
    ],
    required: ['entity_type', 'display_name'],
    labelColumn: 'display_name',
    slugColumn: 'slug',
    naturalKey: ['slug'],
  },
  entity_aliases: {
    writable: ['entity_id', 'alias', 'alias_type', 'source_note'],
    required: ['entity_id', 'alias'],
    labelColumn: 'alias',
    slugColumn: 'alias_slug',
    naturalKey: ['entity_id', 'alias_slug'],
  },
  entity_affiliations: {
    writable: [
      'person_entity_id', 'organization_entity_id', 'role_title', 'context',
      'start_date', 'end_date', 'is_primary', 'is_current', 'evidence_id', 'confidence', 'notes',
    ],
    required: ['person_entity_id', 'organization_entity_id'],
    labelColumn: 'role_title',
    slugColumn: null,
    naturalKey: ['person_entity_id', 'organization_entity_id', 'role_title', 'context'],
  },
  entity_mentions: {
    writable: [
      'mention_text', 'proposed_entity_type', 'proposed_display_name',
      'candidate_entity_id', 'source_evidence_id', 'source_artifact_id', 'business_unit_id',
      'resolution_status', 'confidence', 'rationale', 'created_from',
      'visibility', 'external_use_status', 'sensitivity', 'provenance_note',
    ],
    required: ['mention_text'],
    labelColumn: 'mention_text',
    slugColumn: 'mention_slug',
    naturalKey: ['mention_slug', 'source_evidence_id'],
  },
  evidence: {
    writable: [
      'source_type', 'title', 'url', 'file_reference', 'source_date', 'accessed_at',
      'reliability', 'excerpt', 'notes',
      'visibility', 'external_use_status', 'sensitivity', 'provenance_note',
    ],
    required: ['source_type', 'title'],
    labelColumn: 'title',
    slugColumn: null,
    // A web source is identified by its URL; a captured note has no URL and is
    // identified by `file_reference` = capture:<content hash>, so capturing the
    // same note twice proposes the stored source instead of a duplicate. Only
    // the non-null key columns are compared.
    naturalKey: ['url', 'file_reference'],
  },
  research_artifacts: {
    writable: [
      'title', 'artifact_type', 'summary', 'source_evidence_id', 'capture_source',
      'source_file', 'status', 'created_by',
      'visibility', 'external_use_status', 'sensitivity', 'provenance_note',
    ],
    required: ['title'],
    labelColumn: 'title',
    slugColumn: 'slug',
    naturalKey: ['slug'],
  },
  research_findings: {
    writable: [
      'artifact_id', 'evidence_id', 'related_entity_id', 'business_unit_id',
      'finding_type', 'title', 'content', 'confidence', 'status',
      'visibility', 'external_use_status', 'sensitivity', 'provenance_note',
    ],
    required: ['finding_type', 'title', 'content'],
    labelColumn: 'title',
    slugColumn: null,
    naturalKey: ['title', 'related_entity_id', 'artifact_id'],
  },
  interactions: {
    writable: [
      'interaction_type', 'interaction_direction', 'occurred_at', 'subject', 'summary',
      'external_entity_id', 'internal_business_unit_id', 'internal_owner_member_id',
      'evidence_id', 'source_system', 'source_reference', 'status',
      'visibility', 'external_use_status', 'sensitivity', 'provenance_note',
    ],
    required: ['interaction_type', 'subject'],
    labelColumn: 'subject',
    slugColumn: null,
    naturalKey: ['subject', 'external_entity_id', 'occurred_at'],
  },
  actions: {
    writable: [
      'action_type', 'title', 'description', 'due_at', 'status', 'priority',
      'related_entity_id', 'related_interaction_id', 'internal_business_unit_id',
      'owner_member_id', 'evidence_id', 'source_system', 'source_reference',
      'visibility', 'external_use_status', 'sensitivity', 'provenance_note',
    ],
    required: ['title'],
    labelColumn: 'title',
    slugColumn: null,
    naturalKey: ['title', 'related_entity_id'],
  },
  signals: {
    writable: [
      'signal_type', 'title', 'description', 'priority', 'promotion_trigger',
      'related_entity_id', 'business_unit_id', 'evidence_id', 'status',
      'signal_date', 'signal_strength', 'confidence', 'original_claim',
      'why_it_matters', 'decision_question', 'recommended_next_step',
      'visibility', 'external_use_status', 'sensitivity', 'provenance_note',
    ],
    required: ['signal_type', 'title'],
    labelColumn: 'title',
    slugColumn: null,
    naturalKey: ['title', 'related_entity_id'],
  },
  signal_entities: {
    writable: ['signal_id', 'entity_id', 'role', 'confidence', 'notes'],
    required: ['signal_id', 'entity_id'],
    labelColumn: 'role',
    slugColumn: null,
    naturalKey: ['signal_id', 'entity_id', 'role'],
  },
  opportunities: {
    writable: [
      'title', 'description', 'opportunity_type', 'stage', 'priority',
      'related_entity_id', 'business_unit_id', 'source_signal_id', 'evidence_id',
      'owner_member_id', 'status',
      'visibility', 'external_use_status', 'sensitivity', 'provenance_note',
    ],
    required: ['title'],
    labelColumn: 'title',
    slugColumn: 'slug',
    naturalKey: ['slug'],
  },
  outcomes: {
    writable: [
      'title', 'description', 'outcome_type', 'outcome_date',
      'related_opportunity_id', 'related_action_id', 'related_interaction_id',
      'related_entity_id', 'business_unit_id', 'evidence_id', 'status',
      'visibility', 'external_use_status', 'sensitivity', 'provenance_note',
    ],
    required: ['title'],
    labelColumn: 'title',
    slugColumn: null,
    naturalKey: ['title', 'related_entity_id'],
  },
  // One source supporting one finding. Both sides are references, so this row
  // depends on the finding AND the source item; neither can be written without
  // the other being approved too.
  research_finding_evidence: {
    writable: ['finding_label', 'evidence_label', 'role', 'locator'],
    required: [],
    labelColumn: null,
    slugColumn: null,
    naturalKey: ['finding_id', 'evidence_id'],
  },
  // A research question the review offers. Selecting one creates this row and
  // nothing else: it is a request, not memory, and it starts no search. The
  // run happens only after the separate confirmation in topic-research.ts.
  research_topics: {
    writable: [
      'label', 'target_type', 'research_question', 'why_useful', 'priority',
      'matched_entity_id', 'business_unit_id', 'resolution_status', 'candidate_matches',
      'selected', 'status',
    ],
    required: ['label', 'research_question'],
    labelColumn: 'label',
    slugColumn: null,
    naturalKey: ['label', 'research_question'],
  },
};

/** Columns holding booleans, dates or timestamps, coerced from model strings. */
export const COLUMN_TYPES: Record<string, 'boolean' | 'date' | 'timestamptz' | 'text'> = {
  is_primary: 'boolean',
  is_current: 'boolean',
  start_date: 'date',
  end_date: 'date',
  source_date: 'date',
  signal_date: 'date',
  outcome_date: 'date',
  accessed_at: 'timestamptz',
  occurred_at: 'timestamptz',
  due_at: 'timestamptz',
};

export function tableSpec(table: string): TableSpec {
  const spec = TABLE_SPECS[table];
  if (!spec) throw new Error(`No proposal spec for table "${table}"`);
  return spec;
}
