-- 0016 Columns the existing Globa 3 database has and 0001 did not reconstruct.
--
-- 0001 rebuilt the legacy tables from the archive's references, before the real
-- schema was available. The row export of the existing database
-- (SUPABASE COPY.zip) names columns that 0001 does not have, so loading it into
-- a database built from these migrations would fail on these tables:
--
--   business_units                   order_index
--   members                          role, bio, linkedin_url
--   external_companies               primary_owner_member_id
--   external_contacts                mobile_phone, linkedin_url, primary_owner_member_id
--   meetings                         date
--   relationship_interactions        external_company_id, external_contact_id,
--                                    internal_business_unit_id, internal_owner_member_id,
--                                    interaction_direction, subject, next_steps,
--                                    source_system, source_reference, tags
--   "Globa 3 Automatization & Memory" slug, type, source, status, order_index
--
-- Everything here is additive and idempotent. Columns are nullable even where
-- the source declares NOT NULL, so a database that already holds rows (a local
-- copy) can take this migration; import verification checks the loaded values.
-- Earlier reconstructed columns (members.role_title, meetings.meeting_date,
-- relationship_interactions.company_id, ...) are left in place and untouched.
--
-- References are added as composite (column, workspace_id) foreign keys, the
-- same shape 0006 uses, so a row can only point at a row in its own workspace.

alter table public.business_units
  add column if not exists order_index bigint;

alter table public.members
  add column if not exists role text,
  add column if not exists bio text,
  add column if not exists linkedin_url text;

alter table public.external_companies
  add column if not exists primary_owner_member_id uuid;

alter table public.external_contacts
  add column if not exists mobile_phone text,
  add column if not exists linkedin_url text,
  add column if not exists primary_owner_member_id uuid;

alter table public.meetings
  add column if not exists date date;

alter table public.relationship_interactions
  add column if not exists external_company_id uuid,
  add column if not exists external_contact_id uuid,
  add column if not exists internal_business_unit_id uuid,
  add column if not exists internal_owner_member_id uuid,
  add column if not exists interaction_direction text,
  add column if not exists subject text,
  add column if not exists next_steps text,
  add column if not exists source_system text,
  add column if not exists source_reference text,
  add column if not exists tags text[];

alter table public."Globa 3 Automatization & Memory"
  add column if not exists slug text,
  add column if not exists type text,
  add column if not exists source text,
  add column if not exists status text default 'active';

-- The source uses an identity column. Values from the export are inserted
-- explicitly (allowed by BY DEFAULT); the import tool moves the sequence past
-- the highest loaded value afterwards.
do $$
begin
  if not exists (
    select 1 from information_schema.columns
     where table_schema = 'public'
       and table_name = 'Globa 3 Automatization & Memory'
       and column_name = 'order_index'
  ) then
    alter table public."Globa 3 Automatization & Memory"
      add column order_index smallint generated by default as identity;
  end if;
end $$;

-- Composite parents need (id, workspace_id) to be unique. external_contacts was
-- not a parent before.
do $$
begin
  alter table public.external_contacts
    add constraint external_contacts_id_workspace_key unique (id, workspace_id);
exception
  when duplicate_table or duplicate_object then null;
end $$;

do $$
declare
  m record;
  mappings jsonb := $j$[
    {"t":"external_companies","c":"primary_owner_member_id","p":"members"},
    {"t":"external_contacts","c":"primary_owner_member_id","p":"members"},
    {"t":"relationship_interactions","c":"external_company_id","p":"external_companies"},
    {"t":"relationship_interactions","c":"external_contact_id","p":"external_contacts"},
    {"t":"relationship_interactions","c":"internal_business_unit_id","p":"business_units"},
    {"t":"relationship_interactions","c":"internal_owner_member_id","p":"members"}
  ]$j$::jsonb;
  cname text;
begin
  for m in select * from jsonb_to_recordset(mappings) as x(t text, c text, p text) loop
    cname := left(m.t || '_' || m.c || '_ws_fk', 63);
    begin
      execute format(
        'alter table public.%I add constraint %I
           foreign key (%I, workspace_id) references public.%I(id, workspace_id)
           on update no action on delete no action',
        m.t, cname, m.c, m.p);
    exception
      when duplicate_object or duplicate_table then null;
    end;
  end loop;
end $$;

create index if not exists relationship_interactions_external_company_idx
  on public.relationship_interactions(external_company_id);
create index if not exists relationship_interactions_external_contact_idx
  on public.relationship_interactions(external_contact_id);
create index if not exists relationship_interactions_internal_bu_idx
  on public.relationship_interactions(internal_business_unit_id);

-- Slugs are unique per workspace, as on every other legacy table since 0006.
do $$
begin
  alter table public."Globa 3 Automatization & Memory"
    add constraint globa3_automatization_memory_workspace_slug_key unique (workspace_id, slug);
exception
  when duplicate_table or duplicate_object then null;
end $$;
